name: Testes de Desempenho com k6

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  run-k6-tests:
    runs-on: ubuntu-latest

    steps:
      # Baixa o código do repositório
      - name: Checkout code
        uses: actions/checkout@v3

      # Verifica os arquivos no repositório para depuração
      - name: List project files
        run: ls -R

      # Instala o k6 no ambiente
      - name: Install k6
        run: |
          sudo apt-get update -y
          sudo apt-get install -y gnupg software-properties-common
          curl -s https://dl.k6.io/key.gpg | sudo apt-key add -
          echo "deb https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update -y
          sudo apt-get install -y k6


      # Executa os testes k6
      - name: Run k6 tests
        run: k6 run tests/home.js
